# Generated by Django 4.2.7 on 2023-12-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_delivery_descriptions_ky_delivery_descriptions_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
