# Generated by Django 4.2.3 on 2023-12-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_delivery_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorabledelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_base', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок Приложение для выгодной доставки')),
                ('title_base_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок Приложение для выгодной доставки')),
                ('title_base_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок Приложение для выгодной доставки')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('descriptions', models.TextField(verbose_name='описание')),
                ('descriptions_ky', models.TextField(null=True, verbose_name='описание')),
                ('descriptions_ru', models.TextField(null=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Приложение для выгодной доставки',
                'verbose_name_plural': 'Приложение для выгодной доставки',
            },
        ),
    ]
