# Generated by Django 4.2.7 on 2023-11-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_partnersslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersSlider2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Слайдер партерство',
                'verbose_name_plural': 'Слайдер партерство',
            },
        ),
        migrations.AddField(
            model_name='partners',
            name='global_descriptions',
            field=models.TextField(blank=True, null=True, verbose_name='Описание Локальный таксопарк'),
        ),
        migrations.AddField(
            model_name='partners',
            name='global_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок Локальный таксопарк'),
        ),
        migrations.AddField(
            model_name='partners',
            name='global_title2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок Локальный таксопарк'),
        ),
    ]
