# Generated by Django 4.2.7 on 2023-11-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_partnersslider2_partners_global_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='global_descriptions_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание Локальный таксопарк'),
        ),
        migrations.AddField(
            model_name='partners',
            name='global_descriptions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание Локальный таксопарк'),
        ),
        migrations.AddField(
            model_name='partners',
            name='global_title2_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок Локальный таксопарк'),
        ),
        migrations.AddField(
            model_name='partners',
            name='global_title2_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок Локальный таксопарк'),
        ),
        migrations.AddField(
            model_name='partners',
            name='global_title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок Локальный таксопарк'),
        ),
        migrations.AddField(
            model_name='partners',
            name='global_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок Локальный таксопарк'),
        ),
        migrations.AddField(
            model_name='partnersslider2',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='partnersslider2',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
