# Generated by Django 4.2.7 on 2023-11-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_partners_global_descriptions_ky_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnersslider2',
            options={'verbose_name': 'Слайдер партерство 1', 'verbose_name_plural': 'Слайдер партерство 1'},
        ),
    ]
