# Generated by Django 4.2.3 on 2023-12-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_base_slug_earn_slug_environment_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='req',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пользовательское соглашение'),
        ),
        migrations.AddField(
            model_name='base',
            name='req2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Политика конфиденциальности'),
        ),
        migrations.AddField(
            model_name='base',
            name='req2_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Политика конфиденциальности'),
        ),
        migrations.AddField(
            model_name='base',
            name='req2_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Политика конфиденциальности'),
        ),
        migrations.AddField(
            model_name='base',
            name='req3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Лицензионное соглашение'),
        ),
        migrations.AddField(
            model_name='base',
            name='req3_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Лицензионное соглашение'),
        ),
        migrations.AddField(
            model_name='base',
            name='req3_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Лицензионное соглашение'),
        ),
        migrations.AddField(
            model_name='base',
            name='req_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пользовательское соглашение'),
        ),
        migrations.AddField(
            model_name='base',
            name='req_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пользовательское соглашение'),
        ),
    ]
