# Generated by Django 4.2.7 on 2023-11-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betaxist', '0006_betaxist_join_descriptions_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='betaxist',
            name='earnmoney_descriptions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='КАК ЖЕ НАЧАТЬ ЗАРАБАТЫВАТЬ С ALAGET? (Описание)'),
        ),
        migrations.AddField(
            model_name='betaxist',
            name='earnmoney_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='КАК ЖЕ НАЧАТЬ ЗАРАБАТЫВАТЬ С ALAGET? (Заголовок)'),
        ),
    ]
