# Generated by Django 4.2.7 on 2023-11-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betaxist', '0007_betaxist_earnmoney_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='betaxist',
            name='earnmoney_descriptions_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='КАК ЖЕ НАЧАТЬ ЗАРАБАТЫВАТЬ С ALAGET? (Описание)'),
        ),
        migrations.AddField(
            model_name='betaxist',
            name='earnmoney_descriptions_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='КАК ЖЕ НАЧАТЬ ЗАРАБАТЫВАТЬ С ALAGET? (Описание)'),
        ),
        migrations.AddField(
            model_name='betaxist',
            name='earnmoney_title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='КАК ЖЕ НАЧАТЬ ЗАРАБАТЫВАТЬ С ALAGET? (Заголовок)'),
        ),
        migrations.AddField(
            model_name='betaxist',
            name='earnmoney_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='КАК ЖЕ НАЧАТЬ ЗАРАБАТЫВАТЬ С ALAGET? (Заголовок)'),
        ),
    ]
