# Generated by Django 4.2.7 on 2023-12-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0006_cargo_slug_profitable_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='descriptions2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание Как заказать услугу грузоперезки?'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='descriptions2_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание Как заказать услугу грузоперезки?'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='descriptions2_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание Как заказать услугу грузоперезки?'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='title2',
            field=models.CharField(blank=True, max_length=222, null=True, verbose_name='Заголовок Как заказать услугу грузоперезки?'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='title2_ky',
            field=models.CharField(blank=True, max_length=222, null=True, verbose_name='Заголовок Как заказать услугу грузоперезки?'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='title2_ru',
            field=models.CharField(blank=True, max_length=222, null=True, verbose_name='Заголовок Как заказать услугу грузоперезки?'),
        ),
    ]
