# Generated by Django 4.2.7 on 2023-12-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0011_taxi_advantage1_ky_taxi_advantage1_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='typestaxi',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
